### ISSUE TITLE
Statement closed when unused

### ISSUE THREAD

**Issue by bcarrier** [markmckinnon/Autopsy-Plugins#1]
I got an error on this line on a disk image. I think it needs to be inside the loop so it is closed for each table and only closed if there are tables.  I think my image didn't have tables. 

https://github.com/markmckinnon/Autopsy-Plugins/blob/master/Process_Amcache/ParseAmcache.py#L322

**Comment by markmckinnon** [comment]
Thanks. Will take a look at it and let you know.

**Comment by markmckinnon** [comment]
Would it be possible to get a copy of the image you used?

**Comment by bcarrier** [comment]
It's the Autopsy training image.  Course_Demo_HD_v1.  Do you have a copy of it?

**Comment by markmckinnon** [comment]
Yes I do.  I will take a look at it.  Thanks.

**Comment by markmckinnon** [comment]
This is now fixed.  I moved the stmt and dbconn close statements into their respective loops and added code to check to not process if options in the UI are not checked.  If there is still an issue please reopen this.  Thanks.

**Comment by markmckinnon** [comment]
Closing issue as fixed
