### ISSUE TITLE
Volatility plugin exception in Autopsy 4.5 for Linux.

### ISSUE THREAD

**Issue by danpos** [markmckinnon/Autopsy-Plugins#11]
Hi @markmckinnon 

As stated I have loaded volatility plugin in Python's plugin user directory, to test it out with my new build of Autopsy (for Ubuntu 16.04).

When I load Autopsy, I got an exception (file in attachment).

Just for your information.

Regards,

Danilo.
[Autopsy_Crash_Python_Plugin.txt](https://github.com/markmckinnon/Autopsy-Plugins/files/1628871/Autopsy_Crash_Python_Plugin.txt)

**Comment by markmckinnon** [comment]
Hi Danilo,

I will take a look at it when time permits.

Kind regards.

Mark

**Comment by markmckinnon** [comment]
Try the plugin I uploaded to my google drive to see if it fixes the issue.  If it does I will move it over.
https://drive.google.com/open?id=1zb-vPOQksTaGoFxCv3uSE67VizTekjTU

**Comment by danpos** [comment]
Hi Mark,

Good to hear news about you!

Ok, I will give it a try soon, thank you!

Regards,

Em qua, 26 de set de 2018 18:31, Mark McKinnon <notifications@github.com>
escreveu:

**Comment by markmckinnon** [comment]
I have tested the new version of the plugin on Caine 10.0 and it does work.  I am closing this issue, if it still persists please reopen this issue.
