### ISSUE TITLE
Suggestion Parse_SQLite_Databases

### ISSUE THREAD

**Issue by FHantke** [markmckinnon/Autopsy-Plugins#12]
Hello, 

when I first used your SQLite plugin, I did't realize that I have to click the checkbox after I filled in the textfield and I wonderd  why it did't work. 

My suggestion is that you put line 361 in the getSettings(self) method in line 404. Thus, the content is always add.

https://github.com/markmckinnon/Autopsy-Plugins/blob/35d3baafab0a0cad46fc9365e5e94bc5e78f6ade/Parse_SQLite_Databases/ParseSQLiteDBs.py#L361

Kind regards,

FHantke

**Comment by markmckinnon** [comment]
Have you tried this and did it work?  I just did what you suggested and it die not work.

Kind regards.

Mark

**Comment by FHantke** [comment]
Mhh... you are right, it does not work in your plugin. It works in my own plugin, but I can not reproduce why.
I let you know, as soon as I know more.

**Comment by markmckinnon** [comment]
Shoot me an email at mark dot Mckinnon at davenport dot edu and we can take this offline and look at it further.

**Comment by FHantke** [comment]
Cool, I will send you a Mail as soon as I find time.
