### ISSUE TITLE
Volatility plugin trouble with Autopsy 4.8.0 (windows 10 x64)

### ISSUE THREAD

**Issue by Tonytator** [markmckinnon/Autopsy-Plugins#14]
Hello, 
I have downloaded the volatility plugin in the right folder, but it seems Autopsy can't load it (as well as others plugins). The "Memory Image File" doesn't show up in the "add data source" screen. Can you help me ?
Thank you !
![capture autopsy volatiltiy](https://user-images.githubusercontent.com/43776223/46336984-ab52ef80-c62c-11e8-9934-c049431a7fcc.JPG)
![capture autopsy](https://user-images.githubusercontent.com/43776223/46336985-ab52ef80-c62c-11e8-873b-77f957d7dc48.JPG)

**Comment by markmckinnon** [comment]
Have you downloaded Volatility?  What version is it and are you using the python code or the standalone executable?

**Comment by markmckinnon** [comment]
This has now been fixed.  I am closing the issue, if you still have this issue after installing the new version please reopen this issue.
