### ISSUE TITLE
Problem with Volume Shadow s

### ISSUE THREAD

**Issue by arruw** [markmckinnon/Autopsy-Plugins#17]
I have 4 disks, 2x Ubuntu and 2x Windows 7.
Even when ingesting Ubuntu datasource, I get VSS record in the Datasources section.
Another problem is that every time I run ingest on datasource, new VSS record is created with the same parameters.

![image](https://user-images.githubusercontent.com/9011654/57536369-59054a00-7344-11e9-857c-125170f4dd6c.png)

**Comment by markmckinnon** [comment]
My guess without looking at the code is that it writes the vss data to the same directory without a parent directory over the vss.  You can verify this by going to the case module directory and expanding the vss directory and see what it gives you.  I will take a look at this as soon as I have time.
