### ISSUE TITLE
Getting following error while loading following modules

### ISSUE THREAD

**Issue by xsallowed** [markmckinnon/Autopsy-Plugins#18]
SEVERE: Failed to load PlasoIngestModuleFactory from C:\Users\Administrator\AppData\Roaming\autopsy\python_modules\Plaso\Plaso.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Roaming\autopsy\python_modules\Plaso\Plaso.py", line 74, in <module>
    from org.sleuthkit.autopsy.ingest import GenericIngestModuleJobSettings
ImportError: cannot import name GenericIngestModuleJobSettings

	org.python.core.Py.ImportError(Py.java:328)
	org.python.core.imp.importFromAs(imp.java:1168)
	org.python.core.imp.importFrom(imp.java:1132)
	Plaso$py.f$0(C:\Users\Administrator\AppData\Roaming\autopsy\python_modules\Plaso\Plaso.py:435)
	Plaso$py.call_function(C:\Users\Administrator\AppData\Roaming\autopsy\python_modules\Plaso\Plaso.py)
	org.python.core.PyTableCode.call(PyTableCode.java:167)
	org.python.core.PyCode.call(PyCode.java:18)
	org.python.core.imp.createFromCode(imp.java:436)
	org.python.core.imp.createFromSource(imp.java:396)
	org.python.core.imp.loadFromSource(imp.java:658)
	org.python.core.imp.find_module(imp.java:543)
	org.python.core.imp.import_next(imp.java:840)
	org.python.core.imp.import_module_level(imp.java:959)
	org.python.core.imp.importName(imp.java:1062)
	org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	org.python.core.PyObject.__call__(PyObject.java:431)
	org.python.core.__builtin__.__import__(__builtin__.java:1232)
	org.python.core.imp.importOne(imp.java:1081)
	org.python.pycode._pyx2.f$0(<string>:1)
	org.python.pycode._pyx2.call_function(<string>)
	org.python.core.PyTableCode.call(PyTableCode.java:167)
	org.python.core.PyCode.call(PyCode.java:18)
	org.python.core.Py.runCode(Py.java:1386)
	org.python.core.Py.exec(Py.java:1430)
	org.python.util.PythonInterpreter.exec(PythonInterpreter.java:267)
	org.sleuthkit.autopsy.python.JythonModuleLoader.createObjectFromScript(JythonModuleLoader.java:126)
	org.sleuthkit.autopsy.python.JythonModuleLoader.getInterfaceImplementations(JythonModuleLoader.java:94)
	org.sleuthkit.autopsy.python.JythonModuleLoader.getIngestModuleFactories(JythonModuleLoader.java:57)
	org.sleuthkit.autopsy.ingest.IngestModuleFactoryLoader.getIngestModuleFactories(IngestModuleFactoryLoader.java:123)
	org.sleuthkit.autopsy.ingest.IngestJobSettings.load(IngestJobSettings.java:298)
	org.sleuthkit.autopsy.ingest.IngestJobSettings.<init>(IngestJobSettings.java:150)
	org.sleuthkit.autopsy.ingest.runIngestModuleWizard.IngestModulesConfigWizardPanel.getComponent(IngestModulesConfigWizardPanel.java:70)
	org.sleuthkit.autopsy.ingest.runIngestModuleWizard.RunIngestModulesWizardIterator.<init>(RunIngestModulesWizardIterator.java:60)
	org.sleuthkit.autopsy.ingest.runIngestModuleWizard.RunIngestModulesAction.actionPerformed(RunIngestModulesAction.java:112)
	javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	javax.swing.AbstractButton.doClick(Unknown Source)
	javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	java.awt.Component.processMouseEvent(Unknown Source)
	javax.swing.JComponent.processMouseEvent(Unknown Source)
	java.awt.Component.processEvent(Unknown Source)
	java.awt.Container.processEvent(Unknown Source)
	java.awt.Component.dispatchEventImpl(Unknown Source)
	java.awt.Container.dispatchEventImpl(Unknown Source)
	java.awt.Component.dispatchEvent(Unknown Source)
	java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	java.awt.Container.dispatchEventImpl(Unknown Source)
	java.awt.Window.dispatchEventImpl(Unknown Source)
	java.awt.Component.dispatchEvent(Unknown Source)
	java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	java.awt.EventQueue.access$500(Unknown Source)
	java.awt.EventQueue$3.run(Unknown Source)
	java.awt.EventQueue$3.run(Unknown Source)
	java.security.AccessController.doPrivileged(Native Method)
	java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	java.awt.EventQueue$4.run(Unknown Source)
	java.awt.EventQueue$4.run(Unknown Source)
	java.security.AccessController.doPrivileged(Native Method)
	java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	java.awt.EventQueue.dispatchEvent(Unknown Source)
	org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	java.awt.EventDispatchThread.run(Unknown Source)

**Comment by markmckinnon** [comment]
What version of Autopsy are you using?  The newest Plaso plugin will only work with version 4.7 and above.  If you are using 4.6 then you need the older version of the plugin.
