### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by bcarrier** [markmckinnon/Autopsy-Plugins#2]
Got an index out of range error on an image at this line:

https://github.com/markmckinnon/Autopsy-Plugins/blob/master/Process_EVTX/ParseEvtx.py#L283

I used default settings, which looks like it didn't select any types. Looks like the process() method should do nothing in that case.

**Comment by markmckinnon** [comment]
Thanks.  I will take a look at it.

**Comment by markmckinnon** [comment]
Yes you were correct.  If no events were selected in the UI then the error index out of range would occur.  Added a check at the beginning of the process to gracefully end if there were no event logs selected.  It will also add a message stating this.  Plugin has been fixed, tested and uploaded.  Closing this thread, please reopen if it occurs again.
