### ISSUE TITLE
failure module volatility 

### ISSUE THREAD

**Issue by trirochmadi** [markmckinnon/Autopsy-Plugins#20]
![image](https://user-images.githubusercontent.com/20525701/61587910-1c17c800-abbd-11e9-8b76-a22668262e48.png)
![image](https://user-images.githubusercontent.com/20525701/61587912-2a65e400-abbd-11e9-8159-4738f83a8309.png)
how to overcome this? I use autopsy 4.11.0

**Comment by markmckinnon** [comment]
You will need to install Volatility on your system if you do not already have it. The plugin does not come with it.  If you do not want to install it you can find the installation of volatility in the autopsy third party modules directory in version 4.11. You just need to point the plugin to the exe file in the plugin options panel.
