### ISSUE TITLE
EML_Parser unreadable code

### ISSUE THREAD

**Issue by Lycry** [markmckinnon/Autopsy-Plugins#21]
![TIM图片20191120100541](https://user-images.githubusercontent.com/53429503/69202703-67e37980-0b7d-11ea-9303-4f2de23716d4.png)
![TIM图片20191120100546](https://user-images.githubusercontent.com/53429503/69202705-687c1000-0b7d-11ea-86b6-1cde61bd4552.png)
![TIM图片20191120100602](https://user-images.githubusercontent.com/53429503/69202708-687c1000-0b7d-11ea-844a-9c6b58ce55ba.png)
As shown, when the eml file into Chinese, I can't read correctly in the autopsy plug-in module information, excuse me is there a way to solve.
Thank you!

**Comment by markmckinnon** [comment]
I will have to take a look at this.  Is there a way for you to share a sample email?  If you are using Autopsy 4.13 then it should also handle EML's as well.  My parser should be used for Autopsy versions less than 4.13 since it is now part of Autopsy.

**Comment by Rainytingxve** [comment]
[测试文件.zip](https://github.com/markmckinnon/Autopsy-Plugins/files/3872408/default.zip)
I tried to parse my eml test file using autopsy4.13.0, but he couldn't display my email message, so I had to parse it using the third-party plug-in you published.This is the zip of my eml sample file and I hope it will be helpful to you.
Thank you！

**Comment by markmckinnon** [comment]
Thanks for the sample. I will see what I can do with it. I will also pass it on to Autopsy development team as well so they can see if they can get it to work as well.

**Comment by Rainytingxve** [comment]
Thank you for your reply and look forward to the next features
