### ISSUE TITLE
RingCentral Chat Support

### ISSUE THREAD

**Issue by mastenp** [markmckinnon/Autopsy-Plugins#27]
Would love to see a plugin that parses the chat from a RingCentral Session.  By default the chat log is stored \Documents\RingCentral\Meetings and then a Separate folder for each session named by Date/Time and Ten Digit Room ID (Ex: 2020-05-27 20.39.09 RingCentral Meeting XXXXXXXXXX).

**Comment by markmckinnon** [comment]
Do you have some sample data that I can look at and test with. If you do it would it would make it easier to create the plugin since I will not have to download and create data using the app.

**Comment by mastenp** [comment]
Yes I do, what is the easiest way to get it to you?

**Comment by mastenp** [comment]
[meeting_saved_chat.txt](https://github.com/markmckinnon/Autopsy-Plugins/files/4733964/meeting_saved_chat.txt)
Here is a sample Chat file.  It won't allow me to upload the zip to keep the folder structure.  But this .txt was in the same \Documents\RingCentral\Meetings directory and then in a folder named 2020-06-05 00.13.10 RingCentral Meeting XXXXXXXXXX

**Comment by shannaniggans** [comment]
Created - https://github.com/markmckinnon/Autopsy-Plugins/tree/master/RingCentral
