### ISSUE TITLE
Plugin Py

### ISSUE THREAD

**Issue by Seb95fr** [markmckinnon/Autopsy-Plugins#39]
Hello, no python script appears in autopsy, you know why ?
![Capture](https://user-images.githubusercontent.com/61325138/124774660-44ca3100-df3e-11eb-86d5-c42fa0625d77.JPG)

**Comment by shannaniggans** [comment]
@Seb95fr the screenshot you show has the python modules listed, not sure what the problem is, closing the issue as its old. If you are still having trouble please open another issue with some more details.
