### ISSUE TITLE
Requesting for simple help (How to install these plugins into Autopsy)

### ISSUE THREAD

**Issue by tomamuns** [markmckinnon/Autopsy-Plugins#41]
Hi, 
I am new to Autopsy and requesting for kind help to have the way to install these plugins into Autopsy. 

I have already installed the "NBM" files as well as Python-Plugins, but could not get any for theses, how to install or which physical location to place these plugins. 

I am using Autopsy 4.19.1 in Windows 10 OS

Thanks in advance,
Mamun

**Comment by markmckinnon** [comment]
To install the plugins you download the latest install package executable and that will install them for you.  You can also download this repo as a zip file and unzip the contents to the following directory location c:\Users\XXXX\AppData\Roaming\autopsy\python_plugin where xxxx is your username.  Once that is done then you can remove the following directory as some are for development or have been implemented in Autopsy.  They are Bam_key, Parse_Sam, Parse_Shellbags,  Process_Prefetch_Files_V41, Process_SRUDB, Recycle_Bin, Webcache, wordlist.  All of these are now in Autopsy.  You can also get rid of the folowing directories as they are examples, exe programs, etc for the repo:  Installer, img, gui_test, gui_test_with_settings, Executable Programs For Plugins
