### ISSUE TITLE
We need some README.md files for the main page and all of the plugins

### ISSUE THREAD

**Issue by cogwizzle** [markmckinnon/Autopsy-Plugins#5]
As a user a quick overview of the plugins and a more detailed summary inside of the plugin directory would be really useful for getting started.
Edit: Anyone else feel free to edit and help as well.

**Comment by jfehrman** [comment]
I am working on this issue.

**Comment by markmckinnon** [comment]
Send me an email address and I will send you the docs that I submitted for the plugin contests that might help with documenting things.

**Comment by jfehrman** [comment]
joseph.fehrman@gmail.com

**Comment by jfehrman** [comment]
Started by creating a simple README.md with a summary of all of the plugins.  I will be adding more content as time allows.  https://github.com/markmckinnon/Autopsy-Plugins/pull/6

**Comment by jfehrman** [comment]
Had some additional time.  Added some more docs.  https://github.com/markmckinnon/Autopsy-Plugins/pull/7
