### ISSUE TITLE
SAM Parse Plugin Pulls from RegBack

### ISSUE THREAD

**Issue by coolcalmcollected22** [markmckinnon/Autopsy-Plugins#9]
Good day sir!

When running the Parse SAM option within the Windows Internals plugin, the plugin runs with no problem. However, the source is the SAM file in the RegBack folder and not config. Is this intentional?

**Comment by markmckinnon** [comment]
No it is not.  Are the entries for the username duplicated at all?  I will take a look at the code.  If you run the regular Parse SAM plugin do you get the same results?

**Comment by pcstopper18** [comment]
There were no duplicates, Just the entries for the 1 SAM in RegBack.

I just ran the regular Parse SAM and it pulled all 4 SAM files (config, Regback, windows.old/config & Regback) so no issues with that one.

**Comment by markmckinnon** [comment]
Ok, thanks for doing that.  I will fix the code soon.
